### ISSUE TITLE
(PDOM & Voicing) Simplify wording of edge landmarks

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#279]
In the original Interactive description design for non-visual access, I felt that the outside and inside edges (or landmarks) of the sphere positions needed to be described differently. These landmark descriptions did not result in any negative comments from blind learners. 

Original strings for edge landmarks:
- Track end left/right (for outside edges), and
- Last stop left/right (for inside edges)

However, some slightly negative comments from learners with low vision questioned the need for different words and also the idea of a track (see #277). I'd like to simplify the landmarks strings to all use "Last stop". No need to explicitly call out that the outside edge is the "track end".

Please change to:
- Last stop left/right (for outside and inside edges)

**Comment by jessegreenberg** [comment]
Done in the above commit.

**Comment by jessegreenberg** [comment]
@terracoda can you please verify this is done correctly in https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.0-dev.34/phet/gravity-force-lab-basics_en_phet.html?

**Comment by terracoda** [comment]
The last stop landmarks are working correctly.

I was hoping we could remove the "Left side of track" and "Right side of track", but that string is part of `aria-valuetext. `

Is it the case that it would be a pain to remove that string only from the Voicing feature?

**Comment by jessegreenberg** [comment]
Might not be a pain. Were you envisioning that "Left side of track"/"Right side of track" would just be removed entirely from Voicing? Or that it would be replaced with some other content?

**Comment by terracoda** [comment]
It already says, "Left side of track" and "Right side of track" when a sphere passes the center mark. I think this is done in aria-valuetext.

I was thinking...removing it from "Voicing" if it is straight forward to do so.

**Comment by jessegreenberg** [comment]
Discussed 7/20/21 - @jessegreenberg will remove the "Left side of track" and "Right side of track" strings only in the case of Voicing.

**Comment by jessegreenberg** [comment]
Currently, the object response for the object node is just the aria-valuetext
```js
    // voicing - Update the voicingObjectResponse for each mass when any Property changes that would update the object
    // response
    Property.multilink( [ model.object1.positionProperty, model.object2.positionProperty, model.showDistanceProperty ], () => {
      mass1Node.voicingObjectResponse = mass1Node.ariaValueText;
      mass2Node.voicingObjectResponse = mass2Node.ariaValueText;
    } );
```

The aria-valuetext for the object is created by this in ISLCObjectNode:
```js
a11yCreateAriaValueText: positionDescriber.getPositionAriaValueTextCreator( this.enum ),
```

So we need to create a new function for voicing that returns the content of `getPositionAriaValueTextCreator` without the region information.

**Comment by jessegreenberg** [comment]
Or maybe it would be better to factor out the portion of `getPositionAriaValueTextCreator` that does not include the region information. Then that could be used by voicing AND the original function.

**Comment by jessegreenberg** [comment]
Done in the above commit, "Left side of track"/"Right side of track" removed for Voicing.

**Comment by jessegreenberg** [comment]
@terracoda can you please review in this version? https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.0-dev.36/phet/gravity-force-lab-basics_en_phet.html

**Comment by terracoda** [comment]
The simplified wording for the landmarks is working as requested for both Voicing and the PDOM.
We still have the "Left/Right side of track" in PDOM aria-valuetext and we don't hear that middle indicator in Voicing.

The edge responses have been simplfilied to "Last stop left/right" for both inner and outer edges for both PDOM and Voicing.

Thanks @jessegreenberg. Closing.
